TOKEN = "YOUR_BOT_TOKEN_HERE"
LOG_PATH = "YOUR_LOG_FILE_HERE"
STICKER_IDS = ["YOUR_STICKER_IDS_HERE"]
MINUTES = [0, 10, 20, 30, 40, 50]
DAY_SECONDS = 86400
POINT_LEFT = "\U0001F448"
POINT_RIGHT = "\U0001F449"
BLOCKED_USER_ERROR_CODE = 403
GACHI_STICKER = (
    "CAACAgIAAxkBAAEG0c5jmRSpOJEV_p0KAAGAkuEQYoHmKMsAAqkWAAL5ugFI51be3L04vBAsBA"
)
GAME_TYPES = [
    "🎲 Dice",
    "🎯 Darts",
    "🏀 Basketball",
    "⚽ Football",
    "🎳 Bowling",
    "🎰 Hearthstone",
]
